### ISSUE TITLE
Apache Wicket 9 migration

### ISSUE THREAD

**Issue by sorech02** [immregistries/smm-tester#34]
Tests fail on a migration to Apache Wicket 9, and it seems like there may be additional considerations for the project to stay with the wicket framework.  Junit, inline javascript, perhaps others.  I'm already building with Java 11 in the tests, which is also a need for Wicket 9.

https://cwiki.apache.org/confluence/display/WICKET/Wicket+9.0?src=contextnavchildmode

Wicket 7 still has some security patches, but the developers encourage migration.

**Comment by nathanbunker** [comment]
I think we can take wicket out. I suspect we are not even using this. That was a framework I used to use, but haven't for any of our AIRA projects.
